/**Login action types */
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_STARTED = 'USER_LOGIN_STARTED';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

/***Video fetch action types */
export const VIDEO_FETCH_REQUEST = 'VIDEO_FETCH_REQUEST';
export const VIDEO_FETCH_STARTED = 'VIDEO_FETCH_STARTED';
export const VIDEO_FETCH_SUCCESS = 'VIDEO_FETCH_SUCCESS';
export const VIDEO_FETCH_FAILURE = 'VIDEO_FETCH_FAILURE';

/***strips action types */
export const STRIPS_FETCH_REQUEST = 'STRIPS_FETCH_REQUEST';
export const STRIPS_FETCH_STARTED = 'STRIPS_FETCH_STARTED';
export const STRIPS_FETCH_SUCCESS = 'STRIPS_FETCH_SUCCESS';
export const STRIPS_FETCH_FAILURE = 'STRIPS_FETCH_FAILURE';

